export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const GET_ERRORS = "GET_ERRORS";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_ERROR = "GET_ALL_POSTS_ERROR";
export const LOGUT_SUCCESS = "LOGUT_SUCCESS";

